version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: tumipay_db
    environment:
      POSTGRES_USER: tumipay
      POSTGRES_PASSWORD: tumipay123
      POSTGRES_DB: tumipaydb
    ports:
      - "5432:5432"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
